// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 09:16:08.354 

// PingProtocol description:
// 

#ifndef PingProtocol_h
#define PingProtocol_h

namespace Protocol {

    namespace _PingProtocol {

        enum class SignalIn : char {ping};
        struct MessageIn {
            static constexpr bool hasMsg () { return true; }
            SignalIn signal;
            union {
                uint32_t ping;
            };
        };


        enum class SignalOut : char {};
        struct MessageOut {
            static constexpr bool hasMsg () { return false; }
            SignalOut signal;
        };

    }

    struct PingProtocol {
        using Signal = _PingProtocol::SignalIn;
        using Message = _PingProtocol::MessageIn;
        static Message ping(uint32_t d) { return Message{Signal::ping, {.ping = d}}; }
    };

    struct PingProtocol_conj {
        using Signal = _PingProtocol::SignalOut;
        using Message = _PingProtocol::MessageOut;
    };

    struct PingProtocol_ : PingProtocol, PingProtocol_conj {
    };

}

#endif
