// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.444 

// Potrosac description:
// 

#include "Potrosac_base.h"
#include "checkpoint.h"


namespace Actors {

    void Potrosac_base::createParts (coreid_t host) {
        CHECKPOINT("Potrosac.createParts");
    }

    void Potrosac_base::createConnectors () {
        CHECKPOINT("Potrosac.createConnectors");
    }

}
