// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.444 

// Potrosac description:
// 

#ifndef Potrosac_base_h
#define Potrosac_base_h

#include "ROOM/lib.h"

#if __has_include("actorConfig.h")
    #include "actorConfig.h"
#endif
#include "PingProtocol.h"

using namespace ROOM;
using namespace Protocol;

namespace Actors {


    class Potrosac_base : public Actor {
        public:
            Potrosac_base (Actor* owner = nullptr, coreid_t host = nullcoreid, coreid_t target = nullcoreid)
                : Actor(owner, target) {
                this->createParts(host);
                this->createConnectors();
            }

            static Potrosac_base* create(coreid_t host, coreid_t target) {
                return new (actors) Potrosac_base(nullptr, host, target);
            }

            virtual bool hasSporadicBehavior () const override { return true; }

        public:
            static constexpr size_t ulaz_cap = ULAZ_CAP;
            ServicePort <PingProtocol, PingProtocol_conj, ulaz_cap> ulaz = this;
        private:
            void createParts (coreid_t host);
            void createConnectors ();

    };

}

#endif
