// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.445 

// Potrosac description:
// 

#ifndef Potrosac_h
#define Potrosac_h

#include "RTOS/kernel/api/sporadic_task.h"

#include "Potrosac_base.h"

namespace Actors {

    class Potrosac : public Potrosac_base {
        public:
            Potrosac (Actor* owner = nullptr, coreid_t host = nullcoreid, coreid_t target = nullcoreid)
                : Potrosac_base(owner, host, target) {}

            static Potrosac* create(coreid_t host, coreid_t target) {
                return new (actors) Potrosac(nullptr, host, target);
            }

            virtual bool hasSporadicBehavior () const override { return true; }
            virtual SporadicActorTask* getTask () const override { return static_cast<SporadicActorTask*>(hGetTask()); }

        private:
            virtual SporadicActorTask* createTask () override;

            virtual bool scanPorts () override;
            virtual void behavior () override;

            static Kernel::SporadicParams* tp_ptr;
            static Kernel::TaskConfig cfg;

        #define Actors_Potrosac_Clsdef
            #if __has_include("actors/Potrosac_clsdef.h")
                #include "actors/Potrosac_clsdef.h"
            #endif
        #undef Actors_Potrosac_Clsdef

    };

    inline bool Potrosac::scanPorts () {
        bool ret = false;
        ret = (ulaz.hasNewMsg() || ret);
        return ret;
    }

}

#endif
