// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.445 

// Proba description:
// 

#include "Proba_base.h"
#include "checkpoint.h"

#if __has_include("Proizvodjac.h")
    #include "Proizvodjac.h"
#else
    #include "Proizvodjac_base.h"
#endif

#if __has_include("Potrosac.h")
    #include "Potrosac.h"
#else
    #include "Potrosac_base.h"
#endif


namespace Actors {

const coreid_t proizvodjac_core = nullcoreid;
const coreid_t potrosac_core = nullcoreid;

    void Proba_base::createParts (coreid_t host) {
        CHECKPOINT("Proba.createParts");
        this->proizvodjac = 
            #if __has_include("Proizvodjac.h")
            (proizvodjac_core == host || proizvodjac_core == nullcoreid)
                ? new (actors) Proizvodjac(this, host, proizvodjac_core, 0) :
            #endif
            new (actors) Proizvodjac_base(this, host, proizvodjac_core);

        this->potrosac = 
            #if __has_include("Potrosac.h")
            (potrosac_core == host || potrosac_core == nullcoreid)
                ? new (actors) Potrosac(this, host, potrosac_core, 1) :
            #endif
            new (actors) Potrosac_base(this, host, potrosac_core);

    }

    void Proba_base::createConnectors () {
        CHECKPOINT("Proba.createConnectors");
        this->proizvodjac->izlaz.setOutTarget(&this->potrosac->ulaz);
        this->potrosac->ulaz.setOutTarget(&this->proizvodjac->izlaz);

    }

}
