// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.445 

// Proba description:
// 

#ifndef Proba_base_h
#define Proba_base_h

#include "ROOM/lib.h"

#if __has_include("actorConfig.h")
    #include "actorConfig.h"
#endif

using namespace ROOM;
using namespace Protocol;

namespace Actors {

    class Proizvodjac_base;
    class Potrosac_base;

    class Proba_base : public Actor {
        public:
            Proba_base (Actor* owner = nullptr, coreid_t host = nullcoreid, coreid_t target = nullcoreid)
                : Actor(owner, target) {
                this->createParts(host);
                this->createConnectors();
            }

            static Proba_base* create(coreid_t host, coreid_t target) {
                return new (actors) Proba_base(nullptr, host, target);
            }
        private:
            void createParts (coreid_t host);
            void createConnectors ();

            Proizvodjac_base* proizvodjac = nullptr;

            Potrosac_base* potrosac = nullptr;

    };

}

#endif
