// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.443 

// Proizvodjac description:
// 

#ifndef Proizvodjac_base_h
#define Proizvodjac_base_h

#include "ROOM/lib.h"

#if __has_include("actorConfig.h")
    #include "actorConfig.h"
#endif
#include "PingProtocol.h"

using namespace ROOM;
using namespace Protocol;

namespace Actors {


    class Proizvodjac_base : public Actor {
        public:
            Proizvodjac_base (Actor* owner = nullptr, coreid_t host = nullcoreid, coreid_t target = nullcoreid)
                : Actor(owner, target) {
                this->createParts(host);
                this->createConnectors();
            }

            static Proizvodjac_base* create(coreid_t host, coreid_t target) {
                return new (actors) Proizvodjac_base(nullptr, host, target);
            }

            virtual bool hasSporadicBehavior () const override { return true; }

        public:
            static constexpr size_t izlaz_cap = 1;
            ServicePort <PingProtocol_conj, PingProtocol, izlaz_cap> izlaz = this;
        private:
            void createParts (coreid_t host);
            void createConnectors ();

    };

}

#endif
