// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.443 

// Proizvodjac description:
// 

#include "Proizvodjac_base.h"
#include "checkpoint.h"


namespace Actors {

    void Proizvodjac_base::createParts (coreid_t host) {
        CHECKPOINT("Proizvodjac.createParts");
    }

    void Proizvodjac_base::createConnectors () {
        CHECKPOINT("Proizvodjac.createConnectors");
    }

}
