// Generated by HDS OS code generator
// Date and time of generation: 2026-10-08 12:20:58.444 

// Proizvodjac description:
// 

#ifndef Proizvodjac_h
#define Proizvodjac_h

#include "RTOS/kernel/api/periodic_task.h"

#include "Proizvodjac_base.h"

namespace Actors {

    class Proizvodjac : public Proizvodjac_base {
        public:
            Proizvodjac (Actor* owner = nullptr, coreid_t host = nullcoreid, coreid_t target = nullcoreid)
                : Proizvodjac_base(owner, host, target) {}

            static Proizvodjac* create(coreid_t host, coreid_t target) {
                return new (actors) Proizvodjac(nullptr, host, target);
            }

        private:
            virtual PeriodicActorTask* createTask () override;

            virtual bool scanPorts () override;
            virtual void behavior () override;

            static Kernel::PeriodicParams* tp_ptr;
            static Kernel::TaskConfig cfg;

        #define Actors_Proizvodjac_Clsdef
            #if __has_include("actors/Proizvodjac_clsdef.h")
                #include "actors/Proizvodjac_clsdef.h"
            #endif
        #undef Actors_Proizvodjac_Clsdef

    };

    inline bool Proizvodjac::scanPorts () {
        bool ret = true;
        return ret;
    }

}

#endif
